// Analyze.h : header file
//

/////////////////////////////////////////////////////////////////////////////
// CAnalyzeWnd window

class CAnalyzeWnd : public CWnd
{
   // Construction
public:
   CAnalyzeWnd();

   // Attributes
public:

   // Operations
public:

   // Overrides
   // ClassWizard generated virtual function overrides
   //{{AFX_VIRTUAL(CAnalyzeWnd)
   //}}AFX_VIRTUAL

   // Implementation
public:
   virtual ~CAnalyzeWnd();

   // Generated message map functions
protected:
   //{{AFX_MSG(CAnalyzeWnd)
   // NOTE - the ClassWizard will add and remove member functions here.
   //}}AFX_MSG
   DECLARE_MESSAGE_MAP()
}
;

/////////////////////////////////////////////////////////////////////////////
