// Analyze.cpp : implementation file
//

#include "stdafx.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CAnalyzeWnd

CAnalyzeWnd::CAnalyzeWnd()
{
}

CAnalyzeWnd::~CAnalyzeWnd()
{
}


BEGIN_MESSAGE_MAP(CAnalyzeWnd, CWnd)
   //{{AFX_MSG_MAP(CAnalyzeWnd)
   // NOTE - the ClassWizard will add and remove mapping macros here.
   //}}AFX_MSG_MAP
END_MESSAGE_MAP()


/////////////////////////////////////////////////////////////////////////////
// CAnalyzeWnd message handlers
