//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Logicli.rc
//
#define IDR_MANIFEST                    1
#define IDR_MAINFRAME                   101
#define IDR_LOGICLTYPE                  102
#define IDR_LOGICLTYPE_CNTR_IP          103
#define IDD_ABOUTBOX                    104
#define IDP_BUSY                        105
#define IDP_OLE_INIT_FAILED             106
#define IDD_PROP_RECT                   107
#define IDP_FAILED_TO_CREATE            108
#define IDD_SIMULATE_SETUP              109
#define IDB_OSCILLATOR                  110
#define IDD_PROP_OSCILLATOR             111
#define IDB_LED_OFF                     112
#define IDD_PROP_BUZZER                 113
#define IDD_PROP_SWITCH                 114
#define IDD_PROP_AND                    115
#define IDB_BUZZER_ON                   116
#define IDB_BUZZER_OFF                  117
#define IDD_PROP_LED                    118
#define IDB_SWITCH_ON                   119
#define IDD_PROP_OR                     120
#define IDB_SWITCH_OFF                  121
#define IDD_PROP_LED7                   122
#define IDB_INVERT                      123
#define IDD_PROP_WIRE                   124
#define IDR_PALETTE                     125
#define IDD_PROP_NULL                   126
#define IDB_NULL                        127
#define IDD_PROP_INVERT                 128
#define IDD_PROP_IO_OUT                 129
#define IDD_PROP_IO_IN                  130
#define IDD_PROP_NONE                   131
#define IDD_PROP_SOUND                  132
#define IDD_PROP_FILE_OUT               133
#define IDD_PROP_FILE_IN                134
#define IDD_PROP_MEMORY                 135
#define IDD_PROP_BMP                    136
#define IDD_PROP_TEXT                   137
#define IDB_LED7_ON0                    138
#define IDD_PROP_MUX                    139
#define IDD_PROP_RANDOM                 140
#define IDD_PROP_XOR                    141
#define IDB_LED7_OF1                    142
#define IDD_PROP_CLOCK                  143
#define IDB_LED7_OF2                    144
#define IDD_PROP_TIMER                  145
#define IDB_LED7_OF3                    146
#define IDD_PROP_SIGNALRECEIVER         147
#define IDB_LED7_OF4                    148
#define IDD_PROP_SIGNALSENDER           149
#define IDB_LED7_OF5                    150
#define IDD_PROP_KEYBOARD               151
#define IDB_LED7_OF6                    152
#define IDD_GRID                        153
#define IDB_LED7_ON1                    154
#define IDR_OBJECT_POPUP                155
#define IDB_LED7_ON2                    156
#define IDD_ABOUTMS                     157
#define IDB_LED7_ON3                    158
#define IDB_LED7_ON4                    159
#define IDB_LED7_ON5                    160
#define IDB_LED7_ON6                    161
#define IDD_GOTOPAGE                    162
#define IDB_LED7_OF0                    163
#define IDB_LED7_OFF                    164
#define IDB_LED_ONR                     165
#define IDB_LED_ONY                     166
#define IDB_LED_ONG                     167
#define IDB_IO_OUT                      168
#define IDB_IO_IN                       169
#define IDB_PAGE_OUT                    170
#define IDB_GROUND                      171
#define IDB_LIGHTBULB                   172
#define IDB_WAV                         173
#define IDB_BMP                         174
#define IDB_FILE_IN                     175
#define IDD_TIP                         176
#define IDB_KEYPAD                      177
#define IDD_PROP_NETWORK                178
#define IDD_PROP_NODE                   179
#define IDD_PROP_FLIPFLOP               180
#define IDB_DISPLAY                     181
#define IDD_PROP_ROBOT                  182
#define IDD_PROP_SELECT                 183
#define IDD_PROP_TRISTATE               185
#define IDB_PLUS                        186
#define IDD_PROP_BUS                    187
#define VK_OEM_PLUS                     0xBB
#define IDB_PAGE_IN                     188
#define IDD_PROP_PAUSE                  189
#define IDB_FILE_OUT                    190
#define IDD_PROP_DISPLAY                191
#define CG_IDS_TIPOFTHEDAY              192
#define IDD_PROP_COUNTER                193
#define CG_IDS_TIPOFTHEDAYMENU          194
#define IDD_PROP_PLUS                   195
#define IDD_PROP_GROUND                 196
#define IDD_PROP_ALU                    197
#define IDB_COUNTER4                    198
#define IDB_SWITCH_SLIDE                199
#define IDD_PROP_BITBUCKET              200
#define IDD_PROP_KEYPAD                 201
#define IDD_PROP_ANALYZE                202
#define IDD_PROP_TAPEDRIVE              203
#define IDB_NAND2                       204
#define IDB_NAND3                       205
#define IDB_NAND4                       206
#define IDB_AND2                        207
#define IDB_AND3                        208
#define IDB_AND4                        209
#define IDB_NOR2                        210
#define IDB_NOR3                        211
#define IDB_NOR4                        212
#define IDB_OR2                         213
#define IDB_OR3                         214
#define IDB_OR4                         215
#define IDB_ALU                         216
#define CG_IDS_DIDYOUKNOW               217
#define IDB_LED4_OFF                    218
#define IDB_LED4_ON0                    219
#define IDB_LED4_ON1                    220
#define IDB_LED4_ON2                    221
#define IDB_LED4_ON3                    222
#define IDB_LED4_ON4                    223
#define IDB_LED4_ON5                    224
#define IDB_LED4_ON6                    225
#define IDB_LED4_ON7                    226
#define IDB_LED4_ON8                    227
#define IDB_LED4_ON9                    228
#define IDB_LED4_ONA                    229
#define IDB_LED4_ONB                    230
#define IDB_LED4_ONC                    231
#define IDB_LED4_OND                    232
#define IDB_LED4_ONE                    233
#define IDB_LED4_ONF                    234
#define IDB_BREAK                       235
#define IDB_TURTLE                      236
#define IDB_TURING                      237
#define IDB_STACK                       238
#define IDB_HELP                        239
#define IDB_MOUSE                       240
#define IDB_WAVPLAY                     241
#define IDB_FILEO_IN                    242
#define IDB_FILEO_OUT                   243
#define IDB_KEYBOARD_ON                 244
#define IDB_KEYBOARD_OFF                245
#define CG_IDS_FILE_ABSENT              246
#define IDB_MEMORY                      247
#define IDB_BUFFER                      248
#define IDB_WIRE                        249
#define IDB_WIREB                       250
#define IDB_ALUB                        251
#define IDB_AND2B                       252
#define IDB_AND3B                       253
#define IDB_AND4B                       254
#define IDB_BMPB                        255
#define IDB_BREAKB                      256
#define IDB_BUFFERB                     257
#define IDB_BUZZER_OFFB                 258
#define IDB_BUZZER_ONB                  259
#define IDB_COUNTER4B                   260
#define IDB_DISPLAYB                    261
#define IDB_FILE_INB                    262
#define IDB_FILE_OUTB                   263
#define IDB_FILEO_INB                   264
#define IDB_FILEO_OUTB                  265
#define IDB_GROUNDB                     266
#define CG_IDP_FILE_CORRUPT             267
#define IDB_INVERTB                     268
#define IDB_IO_INB                      269
#define IDB_IO_OUTB                     270
#define CG_IDS_TIPOFTHEDAYHELP          271
#define IDB_KEYBOARD_OFFB               272
#define IDB_KEYBOARD_ONB                273
#define IDB_KEYPADB                     274
#define IDB_LED4_OFFB                   275
#define IDB_LED7_OFFB                   276
#define IDB_LED_OFFB                    277
#define IDB_MEMORYB                     278
#define IDB_NAND2B                      279
#define IDB_NAND3B                      280
#define IDB_NAND4B                      281
#define IDB_NOR2B                       282
#define IDB_NOR3B                       283
#define IDB_NOR4B                       284
#define IDB_NULLB                       285
#define IDB_OR2B                        286
#define IDB_OR3B                        287
#define IDB_OR4B                        288
#define IDB_OSCILLATORB                 289
#define IDB_PAGE_INB                    290
#define IDB_PAGE_OUTB                   291
#define IDB_PLUSB                       292
#define IDB_SWITCH_OFFB                 293
#define IDB_SWITCH_ONB                  294
#define IDB_SWITCH_SLIDEB               295
#define IDB_WAVB                        296
#define IDB_LED_UNKNOWN                 297
#define IDB_LED_ONGB                    298
#define IDB_LED_ONRB                    299
#define IDB_LED_ONYB                    300
#define IDB_DEMUXB                      301
#define IDB_DEMUX                       302
#define IDB_BITBUCKET                   303
#define IDB_RANDOM                      304
#define IDB_BITBUCKETB                  305
#define IDB_RANDOMB                     306
#define IDB_SWITCHM_OFF                 307
#define IDB_SWITCHM_ON                  308
#define IDB_SWITCHM_OFFB                309
#define IDB_SWITCHM_ONB                 310
#define IDB_BREAKON                     311
#define IDB_XOR2                        312
#define IDB_XOR3                        313
#define IDB_XOR4                        314
#define IDB_XNOR2                       315
#define IDB_XNOR3                       316
#define IDB_XNOR4                       317
#define IDB_XNOR2B                      318
#define IDB_XNOR3B                      319
#define IDB_XNOR4B                      320
#define IDB_XOR2B                       321
#define IDB_XOR3B                       322
#define IDB_XOR4B                       323
#define IDB_CLOCK                       324
#define IDB_TIMER                       325
#define IDB_TIMERB                      326
#define IDB_CLOCKB                      327
#define IDB_NETWORK                     328
#define IDB_ROBOT                       329
#define IDB_ROBOTB                      330
#define IDB_NETWORKB                    331
#define IDB_NETWORK_CALL                332
#define IDB_NETWORK_WAIT                333
#define IDB_NETWORK_CALLB               334
#define IDB_NETWORK_WAITB               335
#define IDB_NULL_PU                     336
#define IDB_NULL_PD                     337
#define IDB_FF_RS                       338
#define IDB_FF_DL                       339
#define IDB_FF_CRS                      340
#define IDB_FF_MSRS                     341
#define IDB_FF_JK                       342
#define IDB_FF_MSDL                     343
#define IDB_FF_CRSB                     344
#define IDB_FF_DLB                      345
#define IDB_FF_JKB                      346
#define IDB_FF_MSDLB                    347
#define IDB_FF_MSRSB                    348
#define IDB_FF_RSB                      349
#define IDB_NULL_PDB                    350
#define IDB_NULL_PUB                    351
#define IDB_FF_CRSE                     352
#define IDB_FF_CRSEB                    353
#define IDB_FF_DLE                      354
#define IDB_FF_DLEB                     355
#define IDB_FF_JKE                      356
#define IDB_FF_JKEB                     357
#define IDB_FF_MSDLE                    358
#define IDB_FF_MSDLEB                   359
#define IDB_FF_MSRSE                    360
#define IDB_FF_MSRSEB                   361
#define IDB_DEMUX_3TO8                  362
#define IDB_MUX_8TO1                    363
#define IDB_MUX_4TO1                    364
#define IDB_MUX_2TO1                    365
#define IDB_DEMUX_2TO4                  366
#define IDB_DEMUX_1TO2                  367
#define IDB_DEMUX_1TO2B                 368
#define IDB_DEMUX_2TO4B                 369
#define IDB_DEMUX_3TO8B                 370
#define IDB_MUX_2TO1B                   371
#define IDB_MUX_4TO1B                   372
#define IDB_MUX_8TO1B                   373
#define IDB_ROBOT1                      374
#define IDB_TEXT                        375
#define IDB_TEXT1                       376
#define IDB_TEXTSB                      377
#define IDB_TEXTMB                      378
#define IDB_BMPSB                       379
#define IDB_SELECT_0                    380
#define IDB_SELECT_1                    381
#define IDB_SELECT_2                    382
#define IDB_SELECT_3                    383
#define IDB_SELECT_4                    384
#define IDB_SELECT_5                    385
#define IDB_SELECT_6                    386
#define IDB_SELECT_7                    387
#define IDB_SELECT_8                    388
#define IDB_SELECT_9                    389
#define IDB_SELECT_A                    390
#define IDB_SELECT_B                    391
#define IDB_SELECT_C                    392
#define IDB_SELECT_D                    393
#define IDB_SELECT_E                    394
#define IDB_SELECT_F                    395
#define IDB_LED7_OF7                    396
#define IDB_LED7_ON7                    397
#define IDB_LED4PON0                    398
#define IDB_LED4PON1                    399
#define IDB_LED4PON2                    400
#define IDB_LED4PON3                    401
#define IDB_LED4PON4                    402
#define IDB_LED4PON5                    403
#define IDB_LED4PON6                    404
#define IDB_LED4PON7                    405
#define IDB_LED4PON8                    406
#define IDB_LED4PON9                    407
#define IDB_LED4PONA                    408
#define IDB_LED4PONB                    409
#define IDB_LED4PONC                    410
#define IDB_LED4POND                    411
#define IDB_LED4PONE                    412
#define IDB_LED4PONF                    413
#define IDB_SELECT_0B                   414
#define IDB_SELECT_1B                   415
#define IDB_SELECT_2B                   416
#define IDB_SELECT_3B                   417
#define IDB_SELECT_4B                   418
#define IDB_SELECT_5B                   419
#define IDB_SELECT_6B                   420
#define IDB_SELECT_7B                   421
#define IDB_SELECT_8B                   422
#define IDB_SELECT_9B                   423
#define IDB_SELECT_AB                   424
#define IDB_SELECT_BB                   425
#define IDB_SELECT_CB                   426
#define IDB_SELECT_DB                   427
#define IDB_SELECT_EB                   428
#define IDB_SELECT_FB                   429
#define IDB_ROBOTD                      430
#define IDB_NULL_PD1                    431
#define IDB_NULL_PU1                    432
#define IDB_NULL_PD0                    433
#define IDB_NULL_PU0                    434
#define IDB_NULL_1                      435
#define IDB_NULL_0                      436
#define IDB_NULL_PD1B                   437
#define IDB_NULL_PD0B                   438
#define IDB_NULL_PU1B                   439
#define IDB_NULL_PU0B                   440
#define IDB_NULL_1B                     441
#define IDB_NULL_0B                     442
#define IDB_TRISTATE_BUFFER_LO          443
#define IDB_TRISTATE_INVERT_HI          444
#define IDB_TRISTATE_INVERT_LO          445
#define IDB_TRISTATE_BUFFER_HI          446
#define IDB_TRISTATE_BUFFER_HIB         447
#define IDB_TRISTATE_BUFFER_LOB         448
#define IDB_TRISTATE_INVERT_HIB         449
#define IDB_TRISTATE_INVERT_LOB         450
#define IDB_BUS_8                       451
#define IDB_BUS_8B                      452
#define IDB_BUS_4                       453
#define IDB_BUS_2                       454
#define IDB_BUS_4B                      455
#define IDB_BUS_2B                      456
#define IDB_KEYPAD_0                    457
#define IDB_KEYPAD_1                    458
#define IDB_KEYPAD_2                    459
#define IDB_KEYPAD_3                    460
#define IDB_KEYPAD_4                    461
#define IDB_KEYPAD_5                    462
#define IDB_KEYPAD_6                    463
#define IDB_KEYPAD_7                    464
#define IDB_KEYPAD_8                    465
#define IDB_KEYPAD_9                    466
#define IDB_KEYPAD_A                    467
#define IDB_KEYPAD_B                    468
#define IDB_KEYPAD_C                    469
#define IDB_KEYPAD_D                    470
#define IDB_KEYPAD_E                    471
#define IDB_KEYPAD_F                    472
#define IDB_ROBOTDB                     473
#define IDB_LED4_ONU                    474
#define IDB_LED4PONU                    475
#define IDB_ANALYZE                     476
#define IDB_COUNTER8                    477
#define IDB_COUNTER8B                   478
#define IDB_TAPEDRIVE                   479
#define IDB_TAPEDRIVEB                  480
#define IDB_MEMORY16                    481
#define IDB_MEMORY16B                   482
#define IDB_FF_CRS_PCB                  484
#define IDB_FF_CRS_PC                   485
#define IDB_FF_CRSE_PC                  486
#define IDB_FF_CRSE_PCB                 487
#define IDB_BITMAP1                     488
#define IDB_FF_DL_PC                    489
#define IDB_FF_DL_PCB                   490
#define IDB_FF_DLE_PC                   491
#define IDB_FF_DLE_PCB                  492
#define IDB_FF_JK_PC                    493
#define IDB_FF_JK_PCB                   495
#define IDB_FF_JKE_PC                   496
#define IDB_FF_JKE_PCB                  497
#define IDB_FF_RS_PC                    498
#define IDB_FF_RS_PCB                   499
#define IDC_WEIGHT                      500
#define IDB_FF_MSDL_PC                  500
#define IDC_PENCIL                      501
#define IDB_FF_MSDL_PCB                 501
#define IDC_NOFILL                      502
#define IDB_FF_MSDLE_PC                 502
#define IDC_SIMULATE_UNTIL_HALTED       503
#define IDB_FF_MSDLE_PCB                503
#define IDC_SIMULATE_UNTIL_IDLE         504
#define IDB_FF_MSRS_PCB                 504
#define IDC_SIMULATE_UNTIL_TRIGGERED    505
#define IDB_FF_MSRS_PC                  505
#define IDC_SIMULATE_CYCLES             506
#define IDB_FF_MSRSE_PC                 506
#define IDC_SIMULATE_HELP               507
#define IDB_FF_MSRSE_PCB                507
#define IDC_SIMULATE_NUMBER_CYCLES      508
#define IDB_BITMAP2                     508
#define IDC_SIMULATE_DELAY              509
#define IDC_SIMULATE_DELAYED_CYCLES     510
#define IDC_AND_2INPUTS                 511
#define IDC_OR_4INPUTS                  512
#define IDC_OR_3INPUTS                  513
#define IDC_PROBE_ON                    514
#define IDC_OR_DEMORGAN                 515
#define IDC_PROBE_OFF                   516
#define IDC_OR_BMP                      517
#define IDC_PROBE_NULL                  518
#define IDC_BUZZER_FREQ                 519
#define IDC_PROBE_UNKNOWN               520
#define IDC_AND_3INPUTS                 521
#define IDC_BUZZER_DURATION             522
#define IDC_PROBE_PLUS                  523
#define IDC_AND_4INPUTS                 524
#define IDC_PROBE_MINUS                 525
#define IDC_AND_DEMORGAN                526
#define IDC_PROBE_FLOAT                 527
#define IDC_AND_BMP                     528
#define IDC_OR_2INPUTS                  529
#define IDC_BUZZER_TEST                 530
#define IDC_LED_RED                     531
#define IDC_LED_GREEN                   532
#define IDC_LED_YELLOW                  533
#define IDC_OSCILLATOR_STARTLO          534
#define IDC_OSCILLATOR_LO               535
#define IDC_OSCILLATOR_HI               536
#define IDC_IO_IN_INITIAL               537
#define IDC_SWITCH_INITON               538
#define IDC_SWITCH_MOMENTARY            539
#define IDC_LED_BLINK                   540
#define IDC_LED7_BLINK                  541
#define IDC_LED7_CONSTANT               542
#define IDC_LED7_7INPUTS                543
#define IDC_LED7_4INPUTS                544
#define IDC_LED7_RED                    545
#define IDC_LED7_GREEN                  546
#define IDC_LED7_YELLOW                 547
#define IDC_SWITCH_TOGGLE               548
#define IDC_SWITCH_ON                   549
#define IDC_SWITCH_OFF                  550
#define IDC_LED_CONSTANT                551
#define IDC_IO_IN_ADDRESS               552
#define IDC_IO_OUT_ADDRESS              553
#define IDC_IO_OUT_INITIAL              554
#define IDC_SOUND_COMMANDS              555
#define IDC_SOUND_WAIT                  556
#define IDC_BACKGROUND_FILENAME         557
#define IDC_FILEOUT_FILENAME            558
#define IDC_FILEIN_FILENAME             559
#define IDC_FILEOUT_CHECK               560
#define IDC_FILEIN_CHECK                561
#define IDC_BUZZER_BMBTN                562
#define IDC_AND_BMBTN                   563
#define IDC_FILEIN_BMBTN                564
#define IDC_FILEOUT_BMBTN               565
#define IDC_INVERT_BMBTN                566
#define IDC_IOIN_BMBTN                  567
#define IDC_IOOUT_BMBTN                 568
#define IDC_LED_BMBTN                   569
#define IDC_LED7_BMBTN                  570
#define IDC_NONE_BMBTN                  571
#define IDC_NULL_BMBTN                  572
#define IDC_OR_BMBTN                    573
#define IDC_OSCILLATOR_BMBTN            574
#define IDC_SOUND_BMBTN                 575
#define IDC_SWITCH_BMBTN                576
#define IDC_WIRE_BMBTN                  577
#define IDC_BMP_BMBTN                   578
#define IDC_MEMORY_BMBTN                579
#define IDC_TEXT_BMBTN                  580
#define IDC_TEXT_TEXT                   581
#define IDC_TEXT_HORIZONTAL             582
#define IDC_TEXT_SINGLE                 583
#define IDC_TEXT_VERTICAL               584
#define IDC_TEXT_MULTIPLE               585
#define IDC_INVERT_DEMORGAN             586
#define IDC_MUX_DEMUX                   587
#define IDC_MUX_BMBTN                   588
#define IDC_WIRE_HIDE                   589
#define IDC_WIRE_UPPERLEFT              590
#define IDC_WIRE_LOWERRIGHT             591
#define IDC_WIRE_DIRECT                 592
#define IDC_CHECK1                      593
#define IDC_RANDOM_SEED                 594
#define IDC_RANDOM_BMBTN                595
#define IDC_RANDOM_SPARE                596
#define IDC_XOR_BMBTN                   597
#define IDC_XOR_DEMORGAN                598
#define IDC_XOR_2INPUTS                 599
#define IDC_XOR_3INPUTS                 600
#define IDC_XOR_4INPUTS                 601
#define IDC_TIMER_BMBTN                 602
#define IDC_DELAY                       603
#define IDC_CLOCK_BMBTN                 604
#define IDC_CLOCK_SECONDS               605
#define IDC_CLOCK_HOURS                 606
#define IDC_CLOCK_MINUTES               607
#define IDC_CLOCK_DAYSOFMONTH           608
#define IDC_CLOCK_MONTHS                609
#define IDC_CLOCK_YEARS                 610
#define IDC_CLOCK_SPARE                 611
#define IDC_TIMER_SPARE                 612
#define IDC_SIGNALRECEIVER_BMBTN        613
#define IDC_SIGNALSENDER_BMBTN          614
#define IDC_SIGNALRECEIVER_SIGNALNAME   615
#define IDC_SIGNALSENDER_SIGNALNAME     616
#define IDC_SIGNALRECEIVER_DUMMY        617
#define IDC_SIGNALSENDER_DUMMY          618
#define IDC_KEYBOARD_BMBTN              619
#define IDC_KEYBOARD_ASCII              620
#define IDC_NETWORK_BMBTN               621
#define IDC_NETWORK_MAKE                622
#define IDC_NETWORK_LISTEN              623
#define IDC_NETWORK_NAME                624
#define IDC_NETWORK_SOCKET              625
#define IDC_NODE_PASS                   626
#define IDC_NODE_PULLUP                 627
#define IDC_NODDE_PULLDOWN              628
#define IDC_NODE_PULLDOWN               629
#define IDC_NODE_BMBTN                  630
#define IDC_FLIPFLOP_BMBTN              631
#define IDC_NODE_FLOAT                  632
#define IDC_FLIPFLOP_MSDL               633
#define IDC_NODE_ONE                    634
#define IDC_FLIPFLOP_MSRS               635
#define IDC_NODE_ZERO                   636
#define IDC_FLIPFLOP_JK                 637
#define IDC_FLIPFLOP_RS                 638
#define IDC_FLIPFLOP_DL                 639
#define IDC_FLIPFLOP_CRS                640
#define IDC_FLIPFLOP_EDGE               641
#define IDC_MUX_DEMUX3TO8               642
#define IDC_MUX_DEMUX2TO4               643
#define IDC_MUX_DEMUX1TO2               644
#define IDC_MUX_MUX8TO1                 645
#define IDC_MUX_MUX4TO1                 646
#define IDC_MUX_MUX2TO1                 647
#define IDC_POSITION_X                  648
#define IDC_POSITION_Y                  649
#define IDC_CUSTOM_Y                    650
#define IDC_HOTSPOT_Y                   651
#define IDC_CUSTOM_X                    652
#define IDC_HOTSPOT_X                   653
#define IDC_HOTSPOT_UL                  654
#define IDC_HOTSPOT_UR                  655
#define IDC_HOTSPOT_LL                  656
#define IDC_HOTSPOT_LR                  657
#define IDC_HOTSPOT_CT                  658
#define IDC_HOTSPOT_CENTER              659
#define IDC_ROBOT_FILENAME              660
#define IDC_POSITION_CENTER             661
#define IDC_TEXT_FILENAME               662
#define IDC_POSITION_UL                 663
#define IDC_BMP_FILENAME                664
#define IDC_POSITION_UR                 665
#define IDC_BMP_SINGLE                  666
#define IDC_POSITION_LL                 667
#define IDC_BMP_MULTIPLE                668
#define IDC_POSITION_LR                 669
#define IDC_SELECT_BMBTN                670
#define IDC_POSITION_CT                 671
#define IDC_SELECT_0                    672
#define IDC_SELECT_1                    673
#define IDC_SELECT_2                    675
#define IDC_SELECT_3                    677
#define IDC_SELECT_4                    679
#define IDC_CHECK_PLAYGROUND            680
#define IDC_SELECT_5                    681
#define IDC_STYLE_SEEING                682
#define IDC_SELECT_6                    683
#define IDC_STYLE_DRAWING               684
#define IDC_SELECT_7                    685
#define IDC_STYLE_TOUCHING              686
#define IDC_SELECT_8                    687
#define IDC_ROBOT_BMBTN                 688
#define IDC_SELECT_9                    689
#define IDC_SELECT_A                    690
#define IDC_GRID_WIDTH                  691
#define IDC_SELECT_B                    692
#define IDC_GRID_HEIGHT                 693
#define IDC_SELECT_C                    694
#define IDC_GRID_ENABLE                 695
#define IDC_SELECT_D                    696
#define IDC_TRISTATE_BMBTN              697
#define IDC_SELECT_E                    698
#define IDC_TRISTATE_DEMORGAN           699
#define IDC_SELECT_F                    700
#define IDC_TRISTATE_ASSERT_LO          701
#define IDC_BUS_BMBTN                   702
#define IDC_GRID_CANVASWIDTH            703
#define IDC_BUS_2INPUTS                 704
#define IDC_GRID_CANVASHEIGHT           705
#define IDC_BUS_4INPUTS                 706
#define IDC_BUS_8INPUTS                 707
#define IDC_FILEIN_BINARY               708
#define IDC_FILEIN_ASCII                709
#define IDC_FILEOUT_BINARY              710
#define IDC_FILEOUT_ASCII               711
#define IDC_MEMORY_BINARY               712
#define IDC_MEMORY_ASCII                713
#define IDC_MEMORY_FILENAME             714
#define IDC_PAUSE_BMBTN                 715
#define IDC_DISPLAY_BMBTN               716
#define IDC_COUNTER_BMBTN               717
#define IDC_PLUS_BMBTN                  718
#define IDC_GROUND_BMBTN                719
#define IDC_ALU_BMBTN                   720
#define IDC_BITBUCKET_BMBTN             721
#define IDC_KEYPAD_BMBTN                722
#define IDC_SETUP_UNKNOWN               723
#define IDC_SETUP_LO                    724
#define IDC_SETUP_PULLEDDOWN            725
#define IDC_SETUP_FLOATING              726
#define IDC_ANALYZE_BMBTN               727
#define IDC_ANALYZE_SIGNALNAME          728
#define IDC_ANALYZE_DUMMY               729
#define IDC_COUNTER_INIT                730
#define IDC_COUNTER_4BIT                731
#define IDC_COUNTER_8BIT                732
#define IDC_CUSTOM1                     733
#define IDC_TAPEDRIVE_BMBTN             734
#define IDC_TAPEDRIVE_BINARY            735
#define IDC_TAPEDRIVE_ASCII             736
#define IDC_TAPEDRIVE_FILENAME          737
#define IDC_TAPEDRIVE_CAPACITY          738
#define IDC_SETUP_SIMRATE               739
#define IDC_TAPEDRIVE_STARTPOSITION     740
#define IDC_SETUP_MAXSPEED              741
#define IDC_SETUP_SPECIFYRATE           742
#define IDC_PAGENUMBER                  743
#define IDC_PAGENAME                    744
#define IDC_PAGELIST                    745
#define IDC_BULB                        746
#define IDC_STARTUP                     747
#define IDC_NEXTTIP                     748
#define IDC_TIPSTRING                   749
#define IDC_TIP_FRAME                   750
#define IDC_RADIO1                      751
#define IDC_RADIO2                      752
#define IDC_MEMORY_8BITS                755
#define IDC_MEMORY_16BITS               756
#define IDC_FLIPFLOP_PC                 757
#define ID_BROWSE                       33000
#define ID_EDIT                         33001
#define ID_INDICATOR_CYCLE              33002
#define ID_INDICATOR_PAGE               33003
#define ID_BROWSE_BACKGROUND            33004
#define ID_CANCEL_EDIT                  33005
#define ID_VIEW_GRID                    33006
#define ID_DRAW_SELECT                  33007
#define ID_DRAW_WIRE                    33008
#define ID_DRAW_ANDGATE                 33009
#define ID_DRAW_ORGATE                  33010
#define ID_OBJECT_LINECOLOR             33011
#define ID_OBJECT_FILLCOLOR             33012
#define ID_OBJECT_MOVETOFRONT           33013
#define ID_OBJECT_MOVETOBACK            33014
#define ID_OBJECT_MOVEFORWARD           33015
#define ID_OBJECT_MOVEBACK              33016
#define ID_VIEW_PAPERCOLOR              33017
#define ID_VIEW_SHOWOBJECTS             33018
#define ID_EDIT_PROPERTIES              33019
#define ID_SIMULATE_RUN                 33020
#define ID_SIMULATE_SETUP               33021
#define ID_SIMULATE_STOP                33022
#define ID_DRAW_OSCILLATORGATE          33023
#define ID_DRAW_LEDGATE                 33024
#define ID_DRAW_SWITCHGATE              33025
#define ID_DRAW_BUZZERGATE              33026
#define ID_DRAW_INVERTGATE              33027
#define ID_SIMULATE_DRAW                33028
#define ID_DRAW_NULLGATE                33029
#define ID_DRAW_LED7GATE                33030
#define ID_DRAW_BITMAP                  33031
#define ID_DRAW_ASCIIDISPLAY            33032
#define ID_DRAW_READFILE                33033
#define ID_DRAW_WRITEFILE               33034
#define ID_DRAW_GROUND                  33035
#define ID_DRAW_PORTIN                  33036
#define ID_DRAW_PORTOUT                 33037
#define ID_DRAW_ASCIIKEYBOARD           33038
#define ID_DRAW_SIGNALSENDER            33039
#define ID_DRAW_SIGNALRECEIVER          33040
#define ID_DRAW_PLUS                    33041
#define ID_DRAW_TEXT                    33042
#define ID_DRAW_SOUNDWAVE               33043
#define ID_DRAW_FLIPFLOP                33044
#define ID_DRAW_KEYPAD                  33045
#define ID_DRAW_COUNTER                 33046
#define ID_SIMULATE_PAUSE               33047
#define ID_SIMULATE_STEP                33048
#define ID_SIMULATE_RESET               33049
#define ID_DRAW_BREAK                   33050
#define ID_DRAW_ROBOT                   33051
#define ID_DRAW_TURTLE                  33052
#define ID_DRAW_TURING                  33053
#define ID_DRAW_ALU                     33054
#define ID_DRAW_STACK                   33055
#define ID_DRAW_HELP                    33056
#define ID_DRAW_MOUSE                   33057
#define ID_SIMULATE_PROBE               33058
#define ID_DRAW_MEMORY                  33059
#define ID_SET_FONT                     33060
#define ID_DRAW_MUX                     33061
#define ID_DRAW_DUMMY1                  33062
#define ID_DRAW_DUMMY2                  33063
#define ID_DRAW_BITBUCKET               33064
#define ID_DRAW_RANDOM                  33065
#define ID_HELP_TUTORIAL                33066
#define ID_DRAW_XORGATE                 33067
#define ID_DRAW_CLOCK                   33068
#define ID_DRAW_TIMER                   33069
#define ID_VIEW_NEXTPAGE                33070
#define ID_VIEW_PREVIOUSPAGE            33071
#define ID_DRAW_NETWORK                 33072
#define ID_NET_CONNECTFINISH            33073
#define ID_NET_CONNECTACK               33074
#define ID_NET_ACCEPTFINISH             33075
#define ID_DRAW_SELECTGATE              33076
#define ID_DRAW_SELECTOR                33077
#define ID_VIEW_SNAPTOGRID              33078
#define ID_HELP_EXAMPLES                33079
#define ID_HELP_RELEASENOTES            33080
#define ID_DRAW_TRISTATE                33081
#define ID_DRAW_BUS                     33082
#define ID_SIMULATE_ANALYZE             33084
#define ID_DRAW_ANALYZE                 33085
#define ID_VIEW_ZOOM_IN                 33086
#define ID_VIEW_ZOOM_OUT                33087
#define ID_VIEW_ZOOM_NORMAL             33088
#define ID_DRAW_TAPEDRIVE               33089
#define ID_HELP_ABOUTMS                 33090
#define ID_VIEW_PALETTE                 33091
#define ID_DRAW_SELECTOR_INTERNAL       33092
#define ID_VIEW_GOTOPAGE                33093
#define ID_PALETTEBAR                   33094
#define ID_VIEW_SNAPSELECTIONTOGRID     33095
#define ID_DRAW_BISECTWIRE              33111
#define ID_VIEW_COLORWIRES              33116
#define ID_ESCAPE                       33118
#define ON_SYSCOMMAND                   33132

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        509
#define _APS_NEXT_COMMAND_VALUE         33133
#define _APS_NEXT_CONTROL_VALUE         758
#define _APS_NEXT_SYMED_VALUE           851
#endif
#endif
