// stdafx.cpp : source file that includes just the standard includes
//  stdafx.pch will be the pre-compiled header
//
// Copyright (C) 1993-1994 George Mills and Softronics, Inc. Corporation
// All rights reserved.
//

//  stdafx.obj will contain the pre-compiled type information
#ifndef WINVER					//- Allow use of features specific to Windows 95 and Windows NT 4 or later.
#define WINVER 0x0400			//- Change this to the appropriate value to target Windows 98 and Windows 2000 or later.
#endif

#include "stdafx.h"
